beginner/practicals/config/routes.rb
Rails.application.routes.draw do

  # root route
  root "main#index"


  #get 'categories/index'
  #get 'categories/show'
  #get 'categories/new'
  #get 'categories/edit'
  #get 'categories/delete'
 
  resources :tasks
  resources :categories

  resources :tasks do
    member do
      get :delete
    end
  end

  resources :categories do
    member do
      get :delete
    end
  end


  # adding a custom route with match
  # anytime we see a /about, we send it to main controller, index action via a GET request
  match 'about', to: "main#about", via: :get
  match 'hello', to: "main#hello", via: :get

  # default routes - Rails routing examines the URL to determine which controller and action should be called. get `:controller/(/:action(/:id))` 
  #get 'main/index'
  #get 'tasks/index'
  #get 'tasks/new'
  #get 'tasks/edit'
  #get 'tasks/show'
  #get 'tasks/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

beginner/practicals/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

beginner/practicals/app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

beginner/practicals/app/models/task.rb
class Task < ApplicationRecord

  belongs_to :category, optional: true

end

beginner/practicals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

beginner/practicals/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

beginner/practicals/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # render('index') is the default behaviour
    # render('index')
  end

  def about
    # render('main/about')
    @created_by = 'sai pavan marlakunta'
    @id = params['id']
    @page = params[:page]
    render('about')
  end

  def hello
    redirect_to(action: 'index')
  end
end

beginner/practicals/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.order(:position) 
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    # the instance var @task is made available for ruby-on-rails form helper
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Task.count
      render('new')
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def delete
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :position, :completed, :description)
  end

end

beginner/practicals/app/helpers/application_helper.rb
module ApplicationHelper
end

beginner/practicals/app/helpers/categories_helper.rb
module CategoriesHelper
end

beginner/practicals/app/helpers/main_helper.rb
module MainHelper
end

beginner/practicals/app/helpers/tasks_helper.rb
module TasksHelper
end

beginner/practicals/app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

beginner/practicals/app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

beginner/practicals/app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

beginner/practicals/app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

beginner/practicals/app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

beginner/practicals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

beginner/practicals/app/views/main/about.html.erb
<h2>About</h2>

<p>Description of task_manager.</p>
<p>created by <%= @created_by %></p>

ID=<%= @id %> <br />
Page=<%= @page %> <br />

beginner/practicals/app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application for managing a To-Do list</p>


<%= link_to('Categories', categories_path) %><br />
<%= link_to('Tasks', tasks_path(page: 1) ) %><br />


<%= link_to('About', {action: 'about', page: 5, id: 20}) %>

beginner/practicals/app/views/tasks/_form.html.erb
    <table summary="Task form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>

      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>

      
      <tr>
        <th>Completed</th>
        <td><%= f.check_box(:completed) %></td>
      </tr>


      <tr>
        <th>Description</th>
        <td><%= f.text_area(:description) %></td>
      </tr>

    </table>

beginner/practicals/app/views/tasks/delete.html.erb
<%= link_to("Back to List", tasks_path, class:'back-link') %>

<div class="tasks delete">
  <h2>Delete Task</h2>

  <%= form_for(@task, method: 'delete') do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p>Are you sure you want to permanently delete this task?</p>
    <p><%= @task.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Task") %>
    </div>

  <% end %>
</div>

beginner/practicals/app/views/tasks/edit.html.erb
<%= link_to("Back to List", tasks_path, :class=> 'back-link') %>

<div class="tasks edit">
  <h2>Edit Task</h2>

  <%= form_for(@task) do |f| %>
     <% # url: task_path(@task) , method: 'patch' %>
    
    <%= render(partial: 'form', locals: {f: f}) %>
    <div class="form-buttons">
      <%= f.submit("Edit Task") %>
    </div>

  <% end %>
</div>

beginner/practicals/app/views/tasks/index.html.erb
<%= link_to('Back to Homepage', {controller: 'main', action: 'index'}) %> <br />

<div class="tasks index">
  <h2>Tasks</h2>
  <%= link_to("Add New Task",new_task_path , class: 'action new') %>
  <table class="listing" summary="Task list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Task</th>
      <th>Completed</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.position %></td>
        <td><%= task.name %></td>
        <td><%= task.completed? ? 'Yes' : 'No' %></td>
        <td><%= task.category&.name || '-' %></td>
        <td class="actions">
          <%= link_to("Show", task_path(task), class: 'action show') %>
          <%= link_to("Edit", edit_task_path(task), class: 'action edit') %>
          <%= link_to("Delete", delete_task_path(task), class: 'action delete') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to('Home Page', '/main/index') %> <br />
<%= link_to('First Task', task_path(1)) %> <br />

beginner/practicals/app/views/tasks/new.html.erb
<%= link_to("Back to List", tasks_path, :class=> 'back-link') %>

<div class="tasks new">
  <h2>Create Task</h2>

  <%= form_for(@task) do |f| %>
     <% # url: tasks_path, method: 'post' %>
    
     <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Task") %>
    </div>

  <% end %>
</div>

beginner/practicals/app/views/tasks/show.html.erb
<%= link_to("Back to List", tasks_path, class:'back-link') %> <br />


<div class="tasks show">
  <h2>Show task</h2>

  <div class="actions">
    <%= link_to('Edit', edit_task_path(@task)) %>
    <%= link_to('Delete', delete_task_path(@task)) %>
  </div>

  <table summary="Task detail view">
    <tr>
      <th>Name</th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @task.position %></td>
    </tr>
    <tr>
      <th>Completed</th>
      <td><%= @task.completed? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @task.description %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td><%= @task.category&.name %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at %></td>
    </tr>

  </table>